### ISSUE TITLE
Time columns converted to Date instead of POSIXct

### ISSUE THREAD

**Issue by edvinf** [MikkoVihtakari/BioticExplorer#9] opened 2020-10-30 13:13 UTC
Reading data from an .rds file downloaded from the current deployment on astarte I could not find station parameters stationstarttime or stationstoptime. I expect those data to be in the data set I extracted (coastal survey), and I also had the option for removing empty columns un-checked.

**Comment by iambaim** [comment] 2020-11-02 14:46
I can confirm that this is a bug. The "Remove empty columns" checklist won't function in the database mode as the input data (yearly xmls) have been pre-processed and stored in the database with `stationstarttime` and `stationstoptime` columns removed. See the code [here](https://github.com/MikkoVihtakari/BioticExplorerServer/blob/3fa07c5b9ec442a238f58753763dda3cefc94c52/R/bioticToDatabase.R#L73-L74).

These columns were removed because `stationstarttime` and `stationstoptime` information have been incorporated into `stationstartdate` and `stationstopdate`, respectively in the database.

And yes, we should make this clearer to user (related to #10).

**Comment by edvinf** [comment] 2020-11-02 19:53
It would be nice to avoid the information loss as well, if possible. I gather that time is stored in a richer data-format under the hood, but in the exported rds files 'stationstartdate' contains only date (again referring to the deployment on astarte). The export could be ammended to re-populate the 'stationstarttime' and 'stationstoptime', or the 'stationstartdate' and 'stationstopdate' could reflect the database and contain the hours and seconds, as well as date. I think either solution is fine, but would of course prefer the second option to be clearly documented.

**Comment by edvinf** [comment] 2020-11-11 22:52
I have investigated this a little bit further. It seems to me that the clause on https://github.com/MikkoVihtakari/BioticExplorerServer/blob/3fa07c5b9ec442a238f58753763dda3cefc94c52/R/bioticToDatabase.R#L106 reverts stationstartdate to a date object if 'convertColumns' is set, so that the time information is lost.

I only ran it with the Desktop version, and there seems to be a slight difference from the code you linked, but from inspection of the BioticServer code the remark still seems relevant.

I could offer to implement a change myself, but I would need some help getting aquatinted with how to keep the Desktop and web-version in sync. More importantly, I don't want to implement any solution that goes on accord with previous decisions, so I would have to bother you for an agreement.

**Comment by MikkoVihtakari** [comment] 2020-12-07 07:54
I don't remember why that convertColumns option is still there (it had a function to speed up the script when it was used in the app.R). The `stationstartdate` etc. columns should be POSIXct, not Date. 

Also, perhaps merging date and time columns was not the smartest move...I remember that there was a reason to do this but cannot remember what that reason was :P

If someone had the time, could you try to compile the database by setting the convertColumns = FALSE? I am swamped with other tasks ATM.

**Comment by MikkoVihtakari** [comment] 2021-02-11 10:27
Fixed in https://github.com/MikkoVihtakari/BioticExplorerServer/commit/b5c4f1596b35eada2519eeb132d9c8fe96420370 and  https://github.com/MikkoVihtakari/BioticExplorer/commit/8261c999b71e5e1aafc8f41f86ddfdd527a26b4e

**Closed as completed by MikkoVihtakari** 2021-02-11 10:27 UTC
Labels: bug
